#include log

#var remote.property1: default-value
#var remote.property2: default-value

spring:
  main:
    banner-mode: "off"

foo: bar

remote:
  prop1: ${this@remote.property1}
  prop2: ${this@remote.property2}

logging:
  config: config/logback.xml
  level:
    root: INFO
